Resources:
  # DynamoDB Tables
  GTEmployesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GTEmployes
      AttributeDefinitions:
        - AttributeName: EmployeeID
          AttributeType: S
      KeySchema:
        - AttributeName: EmployeeID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GTTrucksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GTTrucks
      AttributeDefinitions:
        - AttributeName: TruckID
          AttributeType: S
      KeySchema:
        - AttributeName: TruckID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GTDeliveriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GTDeliveries
      AttributeDefinitions:
        - AttributeName: DeliveryID
          AttributeType: S
      KeySchema:
        - AttributeName: DeliveryID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # LambdaFunction
  GTEmployesLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GTGetEmployes
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        ZipFile: |
          const { DynamoDBClient, ScanCommand } = require('@aws-sdk/client-dynamodb');
          const client = new DynamoDBClient();

          exports.handler = async (event) => {
              const params = { TableName: 'GTEmployes' };
              try {
                  const data = await client.send(new ScanCommand(params));
                  return {
                      statusCode: 200,
                      headers: {
                        "Access-Control-Allow-Origin" : "*", // Required for CORS support to work
                        "Access-Control-Allow-Credentials" : true // Required for cookies, authorization headers with HTTPS
                      },
                      body: JSON.stringify(data.Items),
                  };
              } catch (error) {
                  return {
                      statusCode: 500,
                      headers: {
                        "Access-Control-Allow-Origin" : "*", // Required for CORS support to work
                        "Access-Control-Allow-Credentials" : true // Required for cookies, authorization headers with HTTPS
                      },
                      body: JSON.stringify({ error: error.message }),
                  };
              }
          };

      Role: !GetAtt GTLambdaExecutionRole.Arn

  GTTrucksLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GTGetTrucks
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        ZipFile: |
          const { DynamoDBClient, ScanCommand } = require('@aws-sdk/client-dynamodb');
          const client = new DynamoDBClient();

          exports.handler = async (event) => {
              const params = { TableName: 'GTTrucks' };
              try {
                  const data = await client.send(new ScanCommand(params));
                  return {
                      statusCode: 200,
                      headers: {
                        "Access-Control-Allow-Origin" : "*", // Required for CORS support to work
                        "Access-Control-Allow-Credentials" : true // Required for cookies, authorization headers with HTTPS
                      },
                      body: JSON.stringify(data.Items),
                  };
              } catch (error) {
                  return {
                      statusCode: 500,
                      headers: {
                        "Access-Control-Allow-Origin" : "*", // Required for CORS support to work
                        "Access-Control-Allow-Credentials" : true // Required for cookies, authorization headers with HTTPS
                      },
                      body: JSON.stringify({ error: error.message }),
                  };
              }
          };

      Role: !GetAtt GTLambdaExecutionRole.Arn

  GTDeliveriesLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GTGetDeliveries
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        ZipFile: |
          const { DynamoDBClient, ScanCommand } = require('@aws-sdk/client-dynamodb');
          const client = new DynamoDBClient();

          exports.handler = async (event) => {
              const params = { TableName: 'GTDeliveries' };
              try {
                  const data = await client.send(new ScanCommand(params));
                  return {
                      statusCode: 200,
                      headers: {
                        "Access-Control-Allow-Origin" : "*", // Required for CORS support to work
                        "Access-Control-Allow-Credentials" : true // Required for cookies, authorization headers with HTTPS
                      },
                      body: JSON.stringify(data.Items),
                  };
              } catch (error) {
                  return {
                      statusCode: 500,
                      headers: {
                        "Access-Control-Allow-Origin" : "*", // Required for CORS support to work
                        "Access-Control-Allow-Credentials" : true // Required for cookies, authorization headers with HTTPS
                      },
                      body: JSON.stringify({ error: error.message }),
                  };
              }
          };
      Role: !GetAtt GTLambdaExecutionRole.Arn

  GTAddDataLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GTAddData
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        ZipFile: |
          const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
          const { DynamoDBDocumentClient, PutCommand } = require('@aws-sdk/lib-dynamodb');

          const dynamoDBClient = new DynamoDBClient({ region: "eu-central-1" });
          const dynamoDB = DynamoDBDocumentClient.from(dynamoDBClient);

          const deliveriesData = [
              { DeliveryID: '1', deliveryDate: '2024-12-16', destination: 'Paris', status: 'Completed' },
              { DeliveryID: '2', deliveryDate: '2024-12-16', destination: 'Lyon', status: 'Pending' }
          ];

          const trucksData = [
              { TruckID: 'T1', model: 'Volvo', capacity: 20, status: 'Active' },
              { TruckID: 'T2', model: 'Scania', capacity: 25, status: 'Inactive' }
          ];

          const employeesData = [
              { EmployeeID: 'E1', name: 'John Doe', position: 'Driver', status: 'Active' },
              { EmployeeID: 'E2', name: 'Jane Smith', position: 'Mechanic', status: 'Active' }
          ];

          exports.handler = async () => {
              try {
                  const promises = [
                      putItem("GTDeliveries", deliveriesData),
                      putItem("GTTrucks", trucksData),
                      putItem("GTEmployes", employeesData),
                  ];
                  await Promise.all(promises);

                  return {
                      statusCode: 200,
                      body: JSON.stringify({ message: "Data added successfully to all tables" }),
                  };
              } catch (error) {
                  console.error("Error adding data to tables:", error);
                  return {
                      statusCode: 500,
                      body: JSON.stringify({ message: "Failed to add data", error: error.message }),
                  };
              }
          };

          async function putItem(tableName, data) {
              const promises = data.map(item => {
                  const params = {
                      TableName: tableName,
                      Item: item,
                  };
                  return dynamoDB.send(new PutCommand(params));
              });
              await Promise.all(promises);
          }
      Role: !GetAtt GTLambdaExecutionRole.Arn

  GTLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GTLambdaDynamoDBExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GTDynamoDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                Resource: 
                  - !GetAtt GTEmployesTable.Arn
                  - !GetAtt GTTrucksTable.Arn
                  - !GetAtt GTDeliveriesTable.Arn

  # API Gateway
  GTApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: GTCompanyApi

  GTEmployesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt GTApiGateway.RootResourceId
      PathPart: employes
      RestApiId: !Ref GTApiGateway

  GTEmployesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref GTEmployesResource
      RestApiId: !Ref GTApiGateway
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GTEmployesLambdaFunction.Arn}/invocations

  GTEmployesLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GTEmployesLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${GTApiGateway}/*

  GTTrucksResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt GTApiGateway.RootResourceId
      PathPart: trucks
      RestApiId: !Ref GTApiGateway

  GTTrucksMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref GTTrucksResource
      RestApiId: !Ref GTApiGateway
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GTTrucksLambdaFunction.Arn}/invocations

  GTTrucksLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GTTrucksLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${GTApiGateway}/*

  GTDeliveriesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt GTApiGateway.RootResourceId
      PathPart: deliveries
      RestApiId: !Ref GTApiGateway

  GTDeliveriesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref GTDeliveriesResource
      RestApiId: !Ref GTApiGateway
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GTDeliveriesLambdaFunction.Arn}/invocations

  GTDeliveriesLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GTDeliveriesLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${GTApiGateway}/*
  
  GTDataResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt GTApiGateway.RootResourceId
      PathPart: data
      RestApiId: !Ref GTApiGateway

  GTDataMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !Ref GTDataResource
      RestApiId: !Ref GTApiGateway
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GTAddDataLambdaFunction.Arn}/invocations
  
  GTAddDataLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GTAddDataLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${GTApiGateway}/*

  # Deployment and Stage
  GTApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - GTDataMethod
      - GTEmployesMethod
      - GTTrucksMethod
      - GTDeliveriesMethod
    Properties:
      RestApiId: !Ref GTApiGateway
      StageName: prod

  # S3 Bucket
  GTStaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gt-static-website-bucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  GTStaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GTStaticWebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
             - s3:GetObject
             - s3:PutObjectAcl
             - s3:PutObject
            Resource: !Sub '${GTStaticWebsiteBucket.Arn}/*'

Outputs:
  GTApiGatewayUrl:
    Value: !Sub 'https://${GTApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Description: URL de l'API Gateway.
  GTS3WebsiteUrl:
    Value: !Sub 'http://${GTStaticWebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com'
    Description: URL de l'hébergement web statique S3.
