Resources:
  # DynamoDB Tables
  GTOEmployesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GTOEmployes
      AttributeDefinitions:
        - AttributeName: EmployeeID
          AttributeType: S
      KeySchema:
        - AttributeName: EmployeeID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GTOTrucksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GTOTrucks
      AttributeDefinitions:
        - AttributeName: TruckID
          AttributeType: S
      KeySchema:
        - AttributeName: TruckID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GTODeliveriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GTODeliveries
      AttributeDefinitions:
        - AttributeName: DeliveryID
          AttributeType: S
      KeySchema:
        - AttributeName: DeliveryID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # LambdaFunctions
  GTOEmployesLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GTOGetEmployes
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        ZipFile: |
          const AWS = require('aws-sdk');
          const dynamodb = new AWS.DynamoDB.DocumentClient();

          exports.handler = async (event) => {
              const params = { TableName: 'GTOEmployes' };
              try {
                  const data = await dynamodb.scan(params).promise();
                  return {
                      statusCode: 200,
                      body: JSON.stringify(data.Items),
                  };
              } catch (error) {
                  return {
                      statusCode: 500,
                      body: JSON.stringify({ error: error.message }),
                  };
              }
          };
      Role: !GetAtt GTOLambdaExecutionRole.Arn

  GTOTrucksLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GTOGetTrucks
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        ZipFile: |
          const AWS = require('aws-sdk');
          const dynamodb = new AWS.DynamoDB.DocumentClient();

          exports.handler = async (event) => {
              const params = { TableName: 'GTOTrucks' };
              try {
                  const data = await dynamodb.scan(params).promise();
                  return {
                      statusCode: 200,
                      body: JSON.stringify(data.Items),
                  };
              } catch (error) {
                  return {
                      statusCode: 500,
                      body: JSON.stringify({ error: error.message }),
                  };
              }
          };
      Role: !GetAtt GTOLambdaExecutionRole.Arn

  GTODeliveriesLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GTOGetDeliveries
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        ZipFile: |
          const AWS = require('aws-sdk');
          const dynamodb = new AWS.DynamoDB.DocumentClient();

          exports.handler = async (event) => {
              const params = { TableName: 'GTODeliveries' };
              try {
                  const data = await dynamodb.scan(params).promise();
                  return {
                      statusCode: 200,
                      body: JSON.stringify(data.Items),
                  };
              } catch (error) {
                  return {
                      statusCode: 500,
                      body: JSON.stringify({ error: error.message }),
                  };
              }
          };
      Role: !GetAtt GTOLambdaExecutionRole.Arn

  GTOLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GTOLambdaDynamoDBExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GTODynamoDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:GetItem
                Resource: 
                  - !GetAtt GTOEmployesTable.Arn
                  - !GetAtt GTOTrucksTable.Arn
                  - !GetAtt GTODeliveriesTable.Arn

  # API Gateway
  GTOApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: GTOCompanyApi

  GTOEmployesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt GTOApiGateway.RootResourceId
      PathPart: employes
      RestApiId: !Ref GTOApiGateway

  GTOEmployesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref GTOEmployesResource
      RestApiId: !Ref GTOApiGateway
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GTOEmployesLambdaFunction.Arn}/invocations

  GTOTrucksResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt GTOApiGateway.RootResourceId
      PathPart: trucks
      RestApiId: !Ref GTOApiGateway

  GTOTrucksMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref GTOTrucksResource
      RestApiId: !Ref GTOApiGateway
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GTOTrucksLambdaFunction.Arn}/invocations

  GTODeliveriesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt GTOApiGateway.RootResourceId
      PathPart: deliveries
      RestApiId: !Ref GTOApiGateway

  GTODeliveriesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !Ref GTODeliveriesResource
      RestApiId: !Ref GTOApiGateway
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GTODeliveriesLambdaFunction.Arn}/invocations

  #S3 Bucket
  GTOStaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gto-static-website-bucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  GTOStaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GTOStaticWebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: 
              AWS: "arn:aws:iam::719862224486:root"
            Action:
             - s3:GetObject
             - s3:PutObjectAcl
            Resource: !Sub '${GTOStaticWebsiteBucket.Arn}/*'

Outputs:
  GTOApiGatewayUrl:
    Value: !Sub 'https://${GTOApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Description: URL de l'API Gateway.
  # GTOS3WebsiteUrl:
  #   Value: !Sub 'http://${GTOStaticWebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com'
  #   Description: URL de l'hébergement web statique S3.
